"""empty message

Revision ID: 156211b73d8d
Revises: 
Create Date: 2026-03-25 19:59:23.207058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156211b73d8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'reciever_id', 'sender_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('descripción', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('coment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguido_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seguidor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion', sa.String(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Boolean(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('shrared', sa.Boolean(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction')
    op.drop_table('post')
    op.drop_table('follower')
    op.drop_table('coment')
    op.drop_table('user')
    op.drop_table('dm')
    # ### end Alembic commands ###
