"""empty message

Revision ID: 4d9c21aa7e48
Revises: d38299911c72
Create Date: 2026-03-25 20:14:36.792984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9c21aa7e48'
down_revision = 'd38299911c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.drop_column('reciever_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reciever_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
