"""empty message

Revision ID: bd572c1dc740
Revises: bdfba0225a71
Create Date: 2026-03-20 20:31:31.709247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd572c1dc740'
down_revision = 'bdfba0225a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('Profile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
