"""empty message

Revision ID: bdfba0225a71
Revises: a5cffa318ac2
Create Date: 2026-03-20 20:22:14.009968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfba0225a71'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id', 'post_id')
    )
    op.create_table('dm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'reciever_id', 'sender_id')
    )
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.Column('seguidores_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'seguido_id', 'seguidores_id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Boolean(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('shrared', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id', 'post_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion', sa.String(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.Column('Profile_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'Profile_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('usuario', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('foto', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('descripción', sa.String(), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['correo'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('descripción')
        batch_op.drop_column('foto')
        batch_op.drop_column('correo')
        batch_op.drop_column('usuario')
        batch_op.drop_column('nombre')

    op.drop_table('post')
    op.drop_table('interaction')
    op.drop_table('followers')
    op.drop_table('dm')
    op.drop_table('coment')
    # ### end Alembic commands ###
